language: python
python:
  - "3.7"

install:
  - pip install build
  - pip install --upgrade virtualenv
  - wget "https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/local/bin/
  - make reinstall

script:
  - make test

addons:
  chrome: stable
