language: python
python:
  - "3.7"

install:
  - pip install build
  - pip install --upgrade virtualenv
  - chmod +x get_chromedriver.sh
  - ./get_chromedriver.sh
  - make reinstall

script:
  - make test

addons:
  chrome: stable
